export const skillset = [
    "Semantic HTML",
    "CSS",
    "CSS BEM convention",
    "CSS Grid",
    "CSS FlexBox",
    "Media Queries",
    "JavaScript (ES6+)",
    "Immutability",
    "React",
    "Create-react-app",
    "Webpack",
    "Babel",
    "React Hooks",
    "localStorage",
    "Styled-components",
    "custom Hooks",
    "Working with API (fetch, axios)",
    "Redux",
    "Redux Toolkit",
    "Redux-Saga",
    "React Router",
    "Markdown",
    "Teamwork",
    "Error handling",
    "Promises, Async/Await",
    "Git",
    "GitHub Pull Requests & Review",
    "Trello",
    "Scrum",
    "NPM",
];

export const whatToLearnNext = [
    "JS Classes",
    "Node.js",
    "TypeScript",
    "Sass/Less",
    "Bootstrap",
    "jQuery",
];